apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: pgadmin
    namespace: pgadmin
spec:
    interval: 15m
    chart:
        spec:
            chart: pgadmin
            version: 19.6.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: pgadmin
    timeout: 10m
    maxHistory: 3
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
            retries: 3
    uninstall:
        keepHistory: false
    values:
        TZ: Europe/Madrid
        credentials:
            minio:
                accessKey: ${S3_PVC_ACCESSKEY}
                bucket: backup
                encrKey: ${S3_PVC_ENCRYPTKEY}
                name: minio
                path: ""
                secretKey: ${S3_PVC_SECRETKEY}
                type: s3
                url: ${S3_PVC_URL}
        ingress:
            main:
                enabled: false
        persistence:
            config:
                enabled: true
                mountPath: /var/lib/pgadmin
                readOnly: false
                storageClass: ""
                volsync:
                    - name: config 
                      type: restic
                      credentials: minio
                      dest:
                        enabled: true
                      src:
                        enabled: true
        release_name: pgadmin
        resources: {}
        securityContext:
            container:
                UMASK: "0022"
                fsGroup: 5050
                readOnlyRootFilesystem: false
                runAsGroup: 5050
                runAsNonRoot: true
                runAsUser: 5050
            pod:
                fsGroup: 5050
                fsGroupChangePolicy: OnRootMismatch
        service:
            main:
                enabled: true
                type: LoadBalancer
                loadBalancerIP: ""
                ports:
                    main:
                        port: 10024
                        targetPort: 80
                integrations:
                    metallb:
                        enabled: true
        workload:
            main:
                podSpec:
                    containers:
                        main:
                            env:
                                PGADMIN_DEFAULT_EMAIL: ${PGADMIN_ADMIN_EMAIL}
                                PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_ADMIN_PASSWORD}
                            probes:
                                liveness:
                                    enabled: true
                                    path: /misc/ping
                                    type: http
                                readiness:
                                    enabled: true
                                    path: /misc/ping
                                    type: http
                                startup:
                                    enabled: true
                                    path: /misc/ping
                                    type: http
                replicas: 1
                type: Deployment
