apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: mongo-express
    namespace: mongodb
spec:
    interval: 15m
    chart:
        spec:
            chart: mongo-express
            version: 8.7.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: mongo-express
    maxHistory: 3
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
            retries: 3
    uninstall:
        keepHistory: false
    values:
        TZ: Europe/Madrid
        workload:
            main:
                podSpec:
                    containers:
                        main:
                            env:
                                ME_CONFIG_MONGODB_URL: ${MONGODB_ROOT_URL}
                                ME_CONFIG_BASICAUTH_USERNAME: ${MONGOEXPRESS_BASICAUTH_USER}
                                ME_CONFIG_BASICAUTH_PASSWORD: ${MONGOEXPRESS_BASICAUTH_PASS}
        ingress:
            main:
                enabled: true
                hosts:
                    - host: mongoexpress.uberelectronnetwork.cc
                integrations:
                    certManager:
                        certificateIssuer: cloudflare-cert
                        enabled: true
                    traefik:
                        allowCors: false
                        enabled: true
                        entrypoints:
                            - websecure