apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: lldap
    namespace: lldap
spec:
    interval: 15m
    chart:
        spec:
            chart: lldap
            version: 6.0.9
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: lldap
    values:
        TZ: Europe/Madrid
        addons:
            codeserver:
                enabled: false
            netshoot:
                enabled: false
            vpn:
                type: disabled
        cnpg:
            main:
                backups:
                    credentials: backblaze
                    enabled: true
                    retentionPolicy: ""
                    revision: ""
                cluster:
                    instances: 2
                    singleNode: true
                database: lldap
                enabled: true
                hibernate: false
                mode: standalone
                monitoring:
                    disableDefaultQueries: false
                    enablePodMonitor: true
                password: PLACEHOLDERPASSWORD
                pgVersion: 15
                pooler:
                    enabled: false
                recovery:
                    enabled: true
                    backupName: ""
                    credentials: backblaze
                    method: ""
                    revision: ""
                    serverName: ""
                user: lldap
        credentials:
            backblaze:
                accessKey: ${S3_BACKBLAZE_ACCESSKEY}
                bucket: ${S3_BACKBLAZE_BUCKET}
                encrKey: ${S3_BACKBLAZE_ENCRYPTKEY}
                name: backblaze
                path: ""
                secretKey: ${S3_BACKBLAZE_SECRETKEY}
                type: s3
                url: ${S3_BACKBLAZE_URL}
            minio:
                accessKey: ${S3_PVC_ACCESSKEY}
                bucket: backup
                encrKey: ${S3_PVC_ENCRYPTKEY}
                name: minio
                path: ""
                secretKey: ${S3_PVC_SECRETKEY}
                type: s3
                url: ${S3_PVC_URL}
        ingress:
            main:
                enabled: true
                hosts:
                    - host: ldap-server.uberelectronnetwork.cc
                      paths:
                        - path: /
                          pathType: Prefix
                ingressClassName: ""
                integrations:
                    certManager:
                        certificateIssuer: cloudflare-cert
                        enabled: true
                    homepage:
                        enabled: false
                    traefik:
                        allowCors: false
                        enabled: true
                        entrypoints:
                            - websecure
        persistence:
            data:
                enabled: true
                mountPath: /data
                readOnly: false
                storageClass: ""
                volsync:
                    - credentials: minio
                      dest:
                        enabled: false
                      name: app
                      src:
                        enabled: true
                      type: restic
        release_name: lldap
        resources: {}
        securityContext:
            container:
                UMASK: "0022"
                readOnlyRootFilesystem: false
                runAsGroup: 568
                runAsUser: 568
            pod:
                fsGroupChangePolicy: OnRootMismatch
        service:
            ldap:
                enabled: true
                loadBalancerIP: ""
                ports:
                    ldap:
                        enabled: true
                        port: 3890
                type: LoadBalancer
            main:
                enabled: true
                loadBalancerIP: ""
                ports:
                    main:
                        port: 17170
                type: LoadBalancer
        workload:
            main:
                podSpec:
                    containers:
                        main:
                            args:
                                - run
                            command:
                                - /app/lldap
                            env:
                                LLDAP_HTTP_PORT: '{{ .Values.service.main.ports.main.port }}'
                                LLDAP_HTTP_URL: ${LDAP_PUBLIC_URL}
                                LLDAP_JWT_SECRET:
                                    - secretRef:
                                        key: LLDAP_JWT_SECRET
                                        name: secrets
                                LLDAP_LDAP_BASE_DN: ${LDAP_BASEDN}
                                LLDAP_LDAP_PORT: '{{ .Values.service.ldap.ports.ldap.port }}'
                                LLDAP_LDAP_USER_DN: ${LDAP_ADMIN_USER}
                                LLDAP_LDAP_USER_EMAIL: ${LDAP_ADMIN_EMAIL}
                                LLDAP_LDAP_USER_PASS: ${LDAP_ADMIN_PASS}
                                LLDAP_SMTP_OPTIONS__ENABLE_PASSWORD_RESET: false
                                LLDAP_SMTP_OPTIONS__FROM: LLDAP Admin <sender@gmail.com>
                                LLDAP_SMTP_OPTIONS__PASSWORD: ""
                                LLDAP_SMTP_OPTIONS__PORT: 587
                                LLDAP_SMTP_OPTIONS__REPLY_TO: Do not reply <noreply@localhost>
                                LLDAP_SMTP_OPTIONS__SERVER: ""
                                LLDAP_SMTP_OPTIONS__SMTP_ENCRYPTION: STARTTLS
                                LLDAP_SMTP_OPTIONS__USER: ""
                                LLDAP_VERBOSE: false
                                LLDAP_database_url:
                                    secretKeyRef:
                                        key: std
                                        name: cnpg-main-urls
                                LLDAP_key_file: /data/private_key
                                smtp: false
                replicas: 1
                type: Deployment
