apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: teamspeak3
    namespace: teamspeak3
spec:
    interval: 15m
    chart:
        spec:
            chart: teamspeak3
            version: 13.3.4
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: teamspeak3
    maxHistory: 3
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
            retries: 3
    uninstall:
        keepHistory: false
    values:
        TZ: Europe/Madrid
        credentials:
            minio:
                accessKey: ${S3_PVC_ACCESSKEY}
                bucket: backup
                encrKey: ${S3_PVC_ENCRYPTKEY}
                name: minio
                path: ""
                secretKey: ${S3_PVC_SECRETKEY}
                type: s3
                url: ${S3_PVC_URL}
        persistence:
            config:
                enabled: true
                mountPath: /var/run/ts3server
                readOnly: false
                volsync:
                    - name: config
                      type: restic
                      credentials: minio
                      dest:
                          enabled: true
                      src:
                          enabled: true
            data:
                enabled: true
                mountPath: /var/ts3server
                readOnly: false
                volsync:
                    - name: app
                      type: restic
                      credentials: minio
                      dest:
                          enabled: true
                      src:
                          enabled: true
        service:
            main:
                enabled: true
                type: LoadBalancer
                loadBalancerIP: ${TS3_IP}
                ports:
                    main:
                        port: 10011
                        targetPort: 10011
                    query:
                        enabled: true
                        port: 10022
                        targetPort: 10022
                    voice:
                        enabled: true
                        port: 9987
                        protocol: udp
                        targetPort: 9987
                    files:
                        enabled: true
                        port: 30033
                        targetPort: 30033
                integrations:
                    metallb:
                        enabled: true
