apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: teamspeak3
    namespace: teamspeak3
spec:
    interval: 15m
    chart:
        spec:
            chart: teamspeak3
            version: 11.0.8
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: teamspeak3
    maxHistory: 3
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
            retries: 3
    uninstall:
        keepHistory: false
    values:
        TZ: Europe/Madrid
        addons:
            codeserver:
                enabled: false
            netshoot:
                enabled: false
            vpn:
                type: disabled
        credentials:
            minio:
                accessKey: ${S3_PVC_ACCESSKEY}
                bucket: backup
                encrKey: ${S3_PVC_ENCRYPTKEY}
                name: minio
                path: ""
                secretKey: ${S3_PVC_SECRETKEY}
                type: s3
                url: ${S3_PVC_URL}
        persistence:
            config:
                enabled: true
                mountPath: /var/run/ts3server
                readOnly: false
                storageClass: ""
                volsync:
                    - name: config 
                      type: restic
                      credentials: minio
                      dest:
                        enabled: true
                      src:
                        enabled: true
            data:
                enabled: true
                mountPath: /var/ts3server
                readOnly: false
                storageClass: ""
                volsync:
                    - name: app 
                      type: restic
                      credentials: minio
                      dest:
                        enabled: true
                      src:
                        enabled: true
        release_name: teamspeak3
        resources: {}
        securityContext:
            container:
                UMASK: "0022"
                readOnlyRootFilesystem: false
                runAsGroup: 568
                runAsUser: 568
            pod:
                fsGroupChangePolicy: OnRootMismatch
        service:
            files:
                enabled: true
                loadBalancerIP: ""
                ports:
                    files:
                        enabled: true
                        port: 30033
                        targetPort: 30033
                type: LoadBalancer
            main:
                enabled: true
                loadBalancerIP: ""
                ports:
                    main:
                        port: 10011
                        targetPort: 10011
                type: LoadBalancer
            query:
                enabled: true
                loadBalancerIP: ""
                ports:
                    query:
                        enabled: true
                        port: 10022
                        targetPort: 10022
                type: LoadBalancer
            voice:
                enabled: true
                loadBalancerIP: ""
                ports:
                    voice:
                        enabled: true
                        port: 9987
                        protocol: udp
                        targetPort: 9987
                type: LoadBalancer
        workload:
            main:
                podSpec:
                    containers:
                        main:
                            env:
                                TS3SERVER_LICENSE: accept
                            probes:
                                liveness:
                                    type: tcp
                                readiness:
                                    type: tcp
                                startup:
                                    type: tcp
                replicas: 1
                type: Deployment
