apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:XxcykfDYQGj13j2TKikDVtlUiBr3Y8shgOWpN44jMU09DYNQl7OfADzauniXyOFHmy+CGqu++HSsSKALIZKxG0ktU9HpAzbHupXEnc/YSm7QqlIPAqlMc3ssNDS6Juu6SLt3VRTMMTaam41DxqKEKyVDKKHqjSFgW3XbBp7VnFsJ6v0UmMs38Oxvwsr50pKtRab+4+6ywyFh5QIxVoI/v5GeRS40m/lp59Auoi8Dq8bP4MFbMxPc6h/7/aSmJZDThEPgIdl6BM5Mgb2ThsoXekH2MAzQebbO3DtVlvc84fr/KW9HEBm/BZTP8dvSEKaFWXmLMw35lRtwLCSUGvfaSsM9gKtH3jbDIApKRhcmIVuDNgfUxCacxTOresnd6nVA,iv:cPLn4MEK4AjPYrL0WNZKCh6YCnzP96//twyXtcZodS8=,tag:dCF+9yPhZxCoYURBDMQFYA==,type:str]
    identity.pub: ENC[AES256_GCM,data:zPa04qPIXFRjWxxvNMFp2byZYrotVI8aOKkmkHdEmy4kWdsdYQ/u8oVgRBySdNMrsc1quBh5VntllHZZBVgj7nuIbEpzHpKAFGy8iI/49lgQC5osGrpT0pXq4eYVRvHwF2i9Ebbzf6aHrr8TKWADh8MFiFHRVbswmBX6GtrbofVeoNGnEfVHUa1bFi0GiAq1h56nHLkCS1qjdaJ8dm8Ocq9Ik3OXRtMGXa9U4J9xD9nTw4HEwVEaxoB/U0n/xUHYlzrS6rlGumvecV6xXA==,iv:8pdNqzhjxvzZk7rhSlriRWz8qbY6SL0Y4LJoh1egy5A=,tag:k13bawFu5EZvjLZDvv9fZA==,type:str]
    known_hosts: ENC[AES256_GCM,data:xXZk1Luv8ZyMnn6LBmeGRCmNixjSx67eFFW961v5QOOGYIhFJQ2yjodPxQUnz+xYS6xU1gAquy7zLPXTlOwyH3NYI+4k/BCoboYvPwZmt+/9o8uNyuf34Klo2ntjlEmsZT578cjxvEyUq9sNKVBEomTUazx5Ym+GA1mwRX312QKhJyvEt+vtYm1AsYb462ALzUKANHvi3p8t28WHArK8kF8bfcrhkqD8IIBq,iv:M+xABQuL7giUXa1Y/z3f5KcPTacCUcsCKeNqYOCI6+M=,tag:Tw3CwjaMZaBae+fcgXN05w==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVFc4MXRKb3YrRUxERkp5
            SEZIVUtuRWJ5WHRLQlNLaktMVU5XTUljTzFBCjdPTERDV3l4K2NCdnlCY0laMjlt
            OWNaSklucG1tUGl2LzZPSW1NY3lZSTQKLS0tIHJycGljajJQU2lFQ0YyN1ByTDVw
            cS9LUGMvRmJlQ1hzd0xHc1FBOWxCdDAK+RckCxCDebJ/LgZYB3jp/Texx1WJU5nE
            Dcfnj371Ab1gXbkEuLIlnbihhWrkOJani9nSBYFZbqaDLMbcmkpQBA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rq7aah8mfu6fhhp0v592hhfytx788ys2zjzm4yf9atk865lvcqcq6yeday
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-08-03T16:06:22Z"
    mac: ENC[AES256_GCM,data:0nxqIfwCUTBqyilFF//Z/yQcYhsZGr8dGiLns2ULYQnNRStWezFry9OlWqm6QtOS9AvaJkifd6xjOlp8oUA6imdcv0fWX6a0mcjgA654h5QoQgEVk19E6eErdxeqWm62pNoaWQXHXAujrUeqUXgpr6rAAm6goYKp6SG1bvmE3g8=,iv:Z6KkQb3ERm2yQrIFzSZK1XnaAKWD1NeW6N81W8Eibss=,tag:Ly+sJW/UC2vTI0nUBW/SKQ==,type:str]
    shamir_threshold: 3
    version: 3.13.1
