apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ZbJxgWQyiIBQT+peaJSAtj9lQqcD24MxkliospazrmnbC3mUbl047uYO0xm63FkXZttM8YQpiU0a7775M3MX/DMGC8GPZ97vlNPVcWoHC0NEJYUyogVXVm8FG6yrwCzBC8h3nPoVHKXTe9OeE/SyDfMHG9DFC5c3TxXL+34z63ZFoCtAHZXfZaTO2jjddXSUuuzWOjFyVLJNd8Way0V3ulzfj9ayK6iW1xuBFn5uXsR4/1hKsVKBJMaAV04ZwTkLvpAg4HCa7GKchsK2vauFGXuxSnZ2EUNqyURwoOxB+GhPAJx2Tlhs2PoICFx9VCfQHw8/CtCdVInVUPXWPkmtpFpcgKLY7spy0I7hgCR6G8eoOOYTqYGz3hEnDJ0tBAEA,iv:Pn6O136gz35o4qnRgniTfwQlYrQkPHjm+vQmgzqVXEw=,tag:X/G0ALqqw5lvGeaN10paKw==,type:str]
    identity.pub: ENC[AES256_GCM,data:pTrlctGRvgAsjBP62ijEVpSD2Flg7bJUg43brgDXHJyZFe+xE7cUI5B406Sf5rlzah/AUz8ZGwdwVbkXUL0TSLX3UJgJ6A8hZ6lBeqBDP+x+655IipjQuu5hiKgF7Q7qPdlMg6DVD34XCEMbJ7QPqk46NqrWPyGIOnwrm8OcQtQJsiFq32dYmHh68lmezPXg0ght8dWmMjt6iFYmoRQYE1av9Jw3p0ThC/KkI/0mF/Li0/D9LLUkKt7oOa8+XvCCNkyxi+K3x58CfK9peQ==,iv:rTb0RGI/KrwjJeN2zzy0Tr4OnVfUCnGcE/6yhDMb2tY=,tag:cqZj3IMCu06qUIAoLLRysA==,type:str]
    known_hosts: ENC[AES256_GCM,data:3gTg02nS7qeJmYHJ9cT4bfM+xNkRDQ9dSBE2j1hcIwI+bQx2rq5Kojg+uMJHeFFktCuBZcv0wuQ47HYS82Hg/EKCvz7y9myWwkO4OtwT5oDKhQVbksAiF8HqGS04S37zxdtJ81gENC57icBm/y1JcfXhXsxiS2Ct3u7ns9UgOk/2Im9N6YRMJ5J2fXEe0I8Mf7Wr8V/t7nRKqbooNrdSvk44nwLmufNjR/kE,iv:cUSK3kin5NjsW4vw/DccNYqxrawRXgUXslL4a7Yi6os=,tag:92Cab+LPcomH4UKM3J/htA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrRUVSOGdWaFlhVjdva3kr
            RDFTY1k4eVVERTNuWjhVRnYySDg2aUpnMHljCmQ2SUlDQjJjUUtUbkZPZjVYVks5
            Zk1JQ1lCZDJVbDY4c0xSc1dyczBsVVEKLS0tIFdGSGhMKzB1VmkrY3lyZm5qSXlk
            d1Yvdk9UNUNkZ0tXNUc3YVZtQTVPQTAKF3R47oWz5o9XLnb5NQ/zuGug1xGUX6WW
            dQjUf81UL5XqF8TTzudGbf07EChyFLkFap2vjXkF/fbbk+Rfjtbp1A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rq7aah8mfu6fhhp0v592hhfytx788ys2zjzm4yf9atk865lvcqcq6yeday
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-07-27T22:33:16Z"
    mac: ENC[AES256_GCM,data:NmKNfJ9UHspdoenMPWX2YHlZtA1oObn2obEDTsrelIcUTDucAAFW5jzV+iu/+UtnLJuUeN5jqW0f21JZ/mRO2vBnKxiJKaQtfGUbXXcDvPsh1z1qSuhEH+I0j2FkQlWPvnlWaQ/dDrf2I8jD1LkMu4ag4Aq60RnNuzdFe+kH16c=,iv:KGOK1cY3iMr9QSlVpqfRxG/PPD3sAm/yJoeKU9lqKQA=,tag:U1lKjsyyQH3TgE3ZP85plg==,type:str]
    shamir_threshold: 3
    version: 3.13.1
