apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:eEcsTJ7KKftN0jgWh9Ju1cVFArIxrYKcIwxc9m1gnDLqvh9sZ1OGwyMSTrlOdie+6axcYU83d1GOuSAExsHJcUtcVdesqjjetBRygLGW2ewh2NIvEzK4zVAmlmFEljQ7au2T5iySDhYjIIn46pv9TitFoPbde2wFRQo/BelDT0FmgS2tEsPg/l56pHkeGtBPflRiDxsYpiqfQmz3cy/22d7e4Swn9vLTnF30daBjGCdBVOGE5owhvrSTCXtKo9NU818gpCmrexlEF36abGwQy6xyVkhcqT8t7FOifLx5M8WmVMZfFQyXrsDmlnVDgoWsZVodryCLtGnM0SlOgSNLUatfd1vlXddBmypHE/TOMklSnI299KyApSkRWSxqP3fl,iv:8orJu9zjID7usoNUjLN9T6OPmOFy94HUHufSW4mnwW4=,tag:YRQj4J6TGWBrkGII0WMRuA==,type:str]
    identity.pub: ENC[AES256_GCM,data:A6ftamrxTkqr+/9YVyKA6cWcdeNkzs7T1uQGxFtT9eI0YUj5XS9mMRWKiwN8bOPevK+cpi8TrXlIGhIGQ6z8cXw3k97w0Kmu120gZlEIok6UzX5r1Rn4r8SlK9OyM23sYcN8xZO5mb2DnXOnPhX7HdCM0FC0qwm6MoEfxjksklBpaimVGJzNIo0hVUU6StbXpHrZhyWTIJf6fFApvFBZRiEBHvMu3t8nz7UURHcKrWOhP+tR1PgT5nkBCo2H2pJNoy1MhXe2wWaGHsIq4w==,iv:+PuXlncnTWaMcUdMKolT0ndL+hciF/10eP7eGdJ52fo=,tag:f+Tubw8+mpahbUsg21ZQ8g==,type:str]
    known_hosts: ENC[AES256_GCM,data:IGlKflfbl/4xrz6V/4Au2HJ7ijznqxzia0MGdK1AdgTtg8iC7626ncsnL4DT/tHJdyjtrA+DnIQ8S1RULwpfE3CGnDAV53tJO7fQ12nOHp7mBOXZrIDn3XGTYSwDaGkeqsQpaR5EFS+SWIccEvBdtvqFbEOYdvp4YJH5isbK/BoZmKySo29P0VlO4DbeKLjx7ZEPKmi/xrp0FiOyuv031fX3I01DYOK9mhj3,iv:ZB8PXIFlN4Le8I0youaqzUbHWSa6Iwc9yQdhKhDOJT4=,tag:aZunCPygOR6T3Bg+EL4EDg==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEUGJORWtlNkFJZG03TFRF
            NTQzRStzOTNMczdSMnJ4cE5DVkRBT3lBVFRVCmVNaFNJM0V2T2lBSGpNS3JVaHAx
            bVNvZ3Nia2pZUzVaMjRDYXZObnAvcFEKLS0tIFQrUWRjbDFkWWU0RlExV3VWbDAx
            VDFORE9tS0NiTnlVdzlzZ0F4OElIUFkKo+BxZCLxb5OpcAd4EHAk00GUKyFhgHhi
            eXV7w+g4RJGOvVKvDDj+3bLTW8HG9vBfPNVqSA6NuAN7XX1SUMAi1g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rq7aah8mfu6fhhp0v592hhfytx788ys2zjzm4yf9atk865lvcqcq6yeday
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-08-03T16:26:10Z"
    mac: ENC[AES256_GCM,data:Gbf4gJDwLIvZKZEIRSboOS9Zoz9yJWOeD6lg8EqWaVIQnD/vEZIi5yToOl5qrZevbm4hy4HChItcehPQ8iA5aHM7oaJxicnd5friw6bBcLEfxr+x5zbeYanKUzSqWqRdWvMcRADOt2sGCl4Iav2BFT7tNYzMf0f+qhzJ0r4JZZo=,iv:Y3RG6LhS/qbCuYTlVduli2atWoB4Oy2TOY4rGp9zKtI=,tag:l/CuBo/vXHmc00xsg1GW1A==,type:str]
    shamir_threshold: 3
    version: 3.13.1
