apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: nextcloud
    namespace: nextcloud
spec:
    interval: 15m
    chart:
        spec:
            chart: nextcloud
            version: 32.2.12
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: nextcloud
    timeout: 20m
    maxHistory: 3
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
            retries: 3
    uninstall:
        keepHistory: false
    values:
        TZ: Europe/Madrid
        cnpg:
            main:
                backups:
                    enabled: true
                    revision: "3"
                    credentials: backblaze
                    retentionPolicy: 7d
                recovery:
                    enabled: true
                    revision: "2"
                    credentials: backblaze
                    method: object_store
                cluster:
                    instances: 2
                    singleNode: true
                database: nextcloud
                enabled: true
                hibernate: false
                mode: recovery
                monitoring:
                    disableDefaultQueries: false
                    enablePodMonitor: true
                password: C9grZXZSDDQkY39o71Ass6muNq6YqN0n7isCqzbY9cww5Cy4YfZSOtyCCpswcR
                pgVersion: 15
                pooler:
                    enabled: false
                user: nextcloud
        credentials:
            backblaze:
                accessKey: ${S3_BACKBLAZE_ACCESSKEY}
                bucket: ${S3_BACKBLAZE_BUCKET}
                encrKey: ${S3_BACKBLAZE_ENCRYPTKEY}
                name: backblaze
                path: ""
                secretKey: ${S3_BACKBLAZE_SECRETKEY}
                type: s3
                url: ${S3_BACKBLAZE_URL}
            minio:
                accessKey: ${S3_PVC_ACCESSKEY}
                bucket: backup
                encrKey: ${S3_PVC_ENCRYPTKEY}
                name: minio
                path: ""
                secretKey: ${S3_PVC_SECRETKEY}
                type: s3
                url: ${S3_PVC_URL}
        ingress:
            main:
                enabled: true
                hosts:
                    - host: nextcloud.uberelectronnetwork.cc
                      paths:
                        - path: /
                          pathType: Prefix
                      # Paths readded for error on "nextcloud.ingressInjector" fixed on https://github.com/truecharts/public/pull/25447
                integrations:
                    certManager:
                        certificateIssuer: cloudflare-cert
                        enabled: true
                    traefik:
                        allowCors: false
                        enabled: true
                        entrypoints:
                            - websecure
                required: true
        metrics:
            main:
                enabled: false
        nextcloud:
            clamav:
                enabled: true
                file_max_size: -1
                infected_action: only_log
            collabora:
                dictionaries:
                    - en_GB
                    - en_US
                    - es_ES
                enabled: true
                interface_mode: default
                password: ADDSYMBOL{NEXTCLOUD_COLLABORA_ADMIN_PASS}
                username: ${NEXTCLOUD_COLLABORA_ADMIN_USER}
            credentials:
                initialAdminPassword: ${NEXTCLOUD_ADMIN_PASS}
                initialAdminUser: ${NEXTCLOUD_ADMIN_USER}
            expirations:
                activity_expire_days: 90
                trash_retention_obligation: auto
                versions_retention_obligation: auto
            files:
                shared_folder_name: Shared
            general:
                accessIP: 192.168.5.6
                default_phone_region: ES
                force_enable_allow_local_remote_servers: false
                run_optimize: true
            notify_push:
                enabled: true
            php:
                memory_limit: 4G
                upload_limit: 20G
            previews:
                cron: true
                enabled: true
                imaginary: true
                providers:
                    - GIF
                    - JPEG
                    - MarkDown
                    - MP3
                    - OpenDocument
                    - PNG
                    - TXT
                    - PDF
        persistence:
            config:
                enabled: true
                readOnly: false
                storageClass: ""
                volsync:
                    - name: config 
                      type: restic
                      credentials: minio
                      dest:
                        enabled: true
                      src:
                        enabled: true
            data:
                enabled: true
                path: /mnt/MainPool/ServerData/NextCloudUserFiles
                readOnly: false
                server: ${TRUENAS_IP}
                type: nfs
            html:
                enabled: true
                readOnly: false
                storageClass: ""
                volsync:
                    - name: html 
                      type: restic
                      credentials: minio
                      dest:
                        enabled: true
                      src:
                        enabled: true
        release_name: nextcloud
        securityContext:
            container:
                UMASK: "0022"
                runAsGroup: 568
                runAsUser: 568
            pod:
                fsGroupChangePolicy: OnRootMismatch