apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: external-somnia-customers
    namespace: external-app
spec:
    interval: 15m
    chart:
        spec:
            chart: external-service
            version: 15.6.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: external-somnia-customers
    maxHistory: 3
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
            retries: 3
    uninstall:
        keepHistory: false
    values:
        service:
            main:
                type: ExternalIP
                externalIP: ${TRUENAS_IP}
                ports:
                    main:
                        protocol: http
                        port: ${EXTERNALAPP_SOMNIA_CUSTOMERS_PORT}
                        # Target port is the port of the "external service"
                        # Defaults to "port" if not set
        ingress:
            main:
                enabled: true
                hosts:
                    - host: somniacustomers.uberelectronnetwork.cc
                integrations:
                    certManager:
                        certificateIssuer: cloudflare-cert
                        enabled: true
                    traefik:
                        allowCors: false
                        enabled: true
                        entrypoints:
                            - websecure